### ISSUE TITLE
How about single image? How about any object?  Is there any real-case?

### ISSUE THREAD

**Issue by yuedajiong** [naver/dust3r#13]
as title

**Comment by vincent-leroy** [comment]
I'm sorry but I'm not sure to understand what the issue is here, could you clarify your question please?

As detailed in the paper, the network expects pairs of images as input (this is a strict constraint). In the monocular case, we simply pass the same image twice as input (this explains why you end-up with two cameras, even in the monocular case).

You can try with any natural or synthetically generated picture(s), but keep in mind that the network was trained on a limited number of scenes/objects. It might under-perform on unseen data, like humans for example (no human data was included in the training so the network has never seen such data distribution). 
In any case, please understand that we do not provide any guarantee on the faithfulness of the results for a practical use. The goal of this repo is to showcase a demo of the DUSt3R inference model.

**Comment by LaFeuilleMorte** [comment]
I've tried reconstruction from images of which the backgrounds has been segmented (Only the foreground object), Unfortunately the model performed poorly on such cases. Maybe the object itself has too little features?
![image](https://github.com/naver/dust3r/assets/43473814/e637e047-d709-4644-b421-9b2101914247)

Image inputs:
![下载 (13)](https://github.com/naver/dust3r/assets/43473814/d55947e4-ec21-488c-be2f-217a54393416)
![下载 (12)](https://github.com/naver/dust3r/assets/43473814/86f9bfe8-30c2-4f46-aa0f-8a4d44d3eee3)
![下载 (11)](https://github.com/naver/dust3r/assets/43473814/7b24df56-1374-4c13-aad1-9a4a29838631)
![下载 (14)](https://github.com/naver/dust3r/assets/43473814/3926c7f9-ad45-49c3-abd4-f1a4b86182cc)

**Comment by vincent-leroy** [comment]
Hi,
Did you look at the pairwise predictions? If they look bad, indeed it comes from the small visual support... If they look reasonable, it means that the global alignment is the source of the problem (and I suspect it is because we were successful with examples as hard as this one, if not harder).

It might come from the fact that confidences in the constant background are not as low as one would expected and they hinder convergence. 
If you are not afraid of diving into the code and you have the binary masks, you can manually set the confidence of the background to zeros before Global Alignment, like here https://github.com/naver/dust3r/blob/70f0eef65a39dd726cd1b0558afb1beed84f5780/demo.py#L134
e.g. : 
```
output = inference(pairs, model, device, batch_size=batch_size)
# output['pred1']['conf'] *= my_foreground_mask_view1.float() # mask is 0 on background and 1 on foreground 
# output['pred2']['conf'] *= my_foreground_mask_view2.float() # mask is 0 on background and 1 on foreground 
mode = GlobalAlignerMode.PointCloudOptimizer if len(imgs) > 2 else GlobalAlignerMode.PairViewer
```

**Comment by LaFeuilleMorte** [comment]
> # output['pred1']['conf'] *= my_foreground_mask_view1.float() # mask is 0 on background and 1 on foreground 
> # output['pred2']['conf'] *= my_foreground_mask_view2.float() # mask is 0 on background and 1 on foreground

All right, I'll try it. Thank you very much

**Comment by yuedajiong** [comment]
@vincent-leroy

try these two images, maybe you can find something. 

![image__distance_2 00__elevation_000__azimuth_030](https://github.com/naver/dust3r/assets/52232153/7aaac204-0799-41c1-bca5-d14178f72a20)

![image__distance_2 00__elevation_225__azimuth_120](https://github.com/naver/dust3r/assets/52232153/3f5a0c5e-a7bd-4192-9bd0-1c86e963f94b)

**Comment by vincent-leroy** [comment]
Hi @yuedajiong ,
DUSt3R was not trained on images of animals like that, as explained in the paper we train on "Habitat [ 103 ], MegaDepth [ 55], ARKitScenes [25 ], MegaDepth [ 55], Static Scenes 3D [ 68 ], Blended MVS [161 ], ScanNet++ [165 ], CO3D-v2 [93 ] and Waymo [ 121 ]."  
Also the network is designed to handle full images, not masked as what you provide. Processing such masked images would required many changes in various stages of the pipeline (and probably to retrain another network).

**Comment by yuedajiong** [comment]
got it. thanks.

**Comment by swtyree** [comment]
@vincent-leroy, because the confidence values are `>=1`, the code snippet above doesn't work. But the following works with a boolean mask (the negation of the mask above):

```
output = inference(pairs, model, device, batch_size=batch_size)
output['pred1']['conf'][my_background_mask_view1] = 1.0
output['pred2']['conf'][my_background_mask_view2] = 1.0
    # mask is 1 on background and 0 on foreground 
mode = GlobalAlignerMode.PointCloudOptimizer if len(imgs) > 2 else GlobalAlignerMode.PairViewer
```

Cheers!

**Comment by puyiwen** [comment]
@yuedajiong , Hi, I dont know why must 2 rgb input when I choose single image to 3D reconstruction? And I dont know why the same image to model, can get different pred, like pred1 pred2. Can you help me? Thank you very much!!

**Comment by puyiwen** [comment]
@vincent-leroy Hi, sorry to bother you, I still dont know why must put 2 rgb to model, even in the monocular case. Can you help me? Thank you!
