### ISSUE TITLE
Pair Mining & Score Generation

### ISSUE THREAD

**Issue by Nik-V9** [naver/dust3r#146]
Hi, Thanks for releasing the preprocessed pairs for all the datasets!

I've been looking at the scores for BlendedMVS and the score is in the range of [0, 10867.6].

However, the DUSt3R paper cites CrocoV2 for the pair scoring scheme, where the range of the function in CrocoV2 is bounded between [-8, 1].

<img width="452" alt="image" src="https://github.com/user-attachments/assets/68a786cf-6d7a-46bf-ae61-571c9f606c5b">

I was wondering if the pair scoring scheme in DUSt3R is different? If yes, could you provide more details/insights? Also, would it be possible to provide the code used to generate the BlendedMVS pairs?

**Comment by yocabon** [comment]
Hi,
the pairing code we used to prepare the release in indeed a bit different.
When we started working on DUSt3R, we started from the CrocoV2 pairing but the code has evolved since then to include more diverse viewpoints (in croco we wanted to avoid easy/hard pairs. The task in dust3r is different so these choices didn't make sense anymore). I cannot share more details about this at the moment.

**Comment by Nik-V9** [comment]
Ah, I see, No worries! I appreciate the quick response.
