### ISSUE TITLE
'PointCloudOptimizer' object has no attribute '_get_msk_indices'

### ISSUE THREAD

**Issue by cyh2713** [naver/dust3r#48]
Hi, I have a problem calling the `preset_pose `function of the `PointCloudOptimizer `class, I don't find the `_get_msk_indices()` function in the class or the parent class, can you please tell me the way to write this function or the code?

**Comment by vincent-leroy** [comment]
Oh yes, this part of the code is not used in the release so we did not test it...
Note that if you provide all cameras, you can just return a range(n_imgs). Otherwise, it should return indices of the provided cameras. I did not debug it but the function should look something like that ( in the `PointCloudOptimizer` class) :
```
def _get_msk_indices(self, msk): # convert binary mask to indices for view selection
    if msk is None: return range(self.n_imgs) # all cameras were provided, no need for a mask
    assert msk.dtype in (bool, torch.bool, np.bool_)
    assert len(msk) == self.n_imgs
    return np.where(msk)[0] # index of the selected cameras
```

**Comment by cyh2713** [comment]
Thank you, I'll update the code.
